// import { StateGroup } from './country';

export const STATEGROUPS = [{
    letter: 'A',
    names: ['Afghanistan',
    'Aland Islands',
    'Albania',
    'Algeria',
    'American Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antarctica',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',]
  }, 
  {
    letter: 'B',
    names: ['Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia, Plurinational State of',
    'Bonaire, Sint Eustatius and Saba',
    'Bosnia and Herzegovina',
    'Botswana',
    'Bouvet Island',
    'Brazil',
    'British Indian Ocean Territory',
    'Brunei Darussalam',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',]
  },
  {
    letter: 'C',
    names: ['Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Cayman Islands',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Christmas Island',
    'Cocos (Keeling) Islands',
    'Colombia',
    'Comoros',
    'Congo',
    'Democratic Republic of the Congo',
    'Costa Rica',
    //'Côte d'Ivoire',
    'Croatia',
    'Cuba',
    'Curaçao',
    'Cyprus',
    'Czech Republic',]
  }, {
    letter: 'D',
    names: ['Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',]
  },
  {
    letter: 'E',
    names: ['Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Ethiopia',]
  },
  {
    letter: 'F',
    names: ['Falkland Islands (Malvinas)',
    'Faroe Islands',
    'Fiji',
    'Finland',
    'France',
    'French Guiana',
    'French Polynesia',
    'French Southern Territories',
    ]
  }, {
    letter: 'G',
    names: ['Gabon',
    'Gambia',
    'Georgia',
    'Ghana',
    'Gibraltar',
    'Greece',
    'Greenland',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',]
  }, {
    letter: 'H',
    names: ['Haiti',
    'Heard Island and McDonald Islands',
    'Honduras',
    'Hong Kong',
    'Hungary',]
  }, {
    letter: 'I',
    names: ['Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Isle of Man',
    'Israel',
    'Italy',]
  },
  {
    letter : 'J',
    names: ['Jamaica',
    'Japan',
    'Jersey',
    'Jordan',]

  },
   {
    letter: 'K',
    names: ['Kazakhstan',
    'Kenya',
    'Kiribati',
    'North Korea',
    'Sourth Korea',
    'Kuwait',
    'Kyrgyzstan',]
  }, {
    letter: 'L',
    names: ['Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',]
  }, {
    letter: 'M',
    names: ['Macao',
    'Republic of Northern Macedonia,',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Mexico',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Myanmar',]
  }, {
    letter: 'N',
    names: ['Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Caledonia',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Norfolk Island',
    'Northern Mariana Islands',
    'Norway',]
  }, {
    letter: 'O',
    names: ['Oman',]
  }, {
    letter: 'P',
    names: ['Pakistan',
    'Palau',
    'State of Palestine',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Pitcairn',
    'Poland',
    'Portugal',
    'Puerto Rico',]
  }, 
  {
    letter : 'Q',
    names: ['Qatar',]
  },
    {
    letter: 'R',
    names: ['Réunion',
    'Romania',
    'Russian Federation',
    'Rwanda',]
  }, {
    letter: 'S',
    names: ['Saint Barthélemy',
    'Ascension and Tristan da Cunha Saint Helena',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Martin (French part)',
    'Saint Pierre and Miquelon',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten (Dutch part)',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Georgia and the South Sandwich Islands',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Svalbard and Jan Mayen',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syrian Arab Republic',]
  }, {
    letter: 'T',
    names: ['Taiwan, Province of China',
    'Tajikistan',
    'United Republic of Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Turks and Caicos Islands',
    'Tuvalu',]
  }, {
    letter: 'U',
    names: ['Uganda',
    'UKraine',
    'United Arab Emirates',
    'United Kingdom of Great Britain and Northern Ireland',
    'United States Minor Outlying Islands',
    'United States of America',
    'Uruguay',
    'Uzbekistan',]
  }, {
    letter: 'V',
    names: ['Vanuatu',
    'Vatican City State (Holy See)',
    'Bolivarian Republic of Venezuela',
    'Viet Nam',
    'Virgin Islands, British',
    'Virgin Islands, U.S.',]
  }, {
    letter: 'W',
    names: ['Wallis and Futuna',
    'Western Sahara',]
  },
{
  letter: 'Y',
  names:['Yemen',]
},
{
  letter: 'Z',
  names:['Zambia',
  'Zimbabwe']
}];


//   countriesList: string[] = [
    
// 'Afghanistan',
// 'Aland Islands',
// 'Albania',
// 'Algeria',
// 'American Samoa',
// 'Andorra',
// 'Angola',
// 'Anguilla',
// 'Antarctica',
// 'Antigua and Barbuda',
// 'Argentina',
// 'Armenia',
// 'Aruba',
// 'Australia',
// 'Austria',
// 'Azerbaijan',
// 'Bahamas',
// 'Bahrain',
// 'Bangladesh',
// 'Barbados',
// 'Belarus',
// 'Belgium',
// 'Belize',
// 'Benin',
// 'Bermuda',
// 'Bhutan',
// 'Bolivia, Plurinational State of',
// 'Bonaire, Sint Eustatius and Saba',
// 'Bosnia and Herzegovina',
// 'Botswana',
// 'Bouvet Island',
// 'Brazil',
// 'British Indian Ocean Territory',
// 'Brunei Darussalam',
// 'Bulgaria',
// 'Burkina Faso',
// 'Burundi',
// 'Cabo Verde',
// 'Cambodia',
// 'Cameroon',
// 'Cayman Islands',
// 'Central African Republic',
// 'Chad',
// 'Chile',
// 'China',
// 'Christmas Island',
// 'Cocos (Keeling) Islands',
// 'Colombia',
// 'Comoros',
// 'Congo',
// 'Democratic Republic of the Congo',
// 'Costa Rica',
// //'Côte d'Ivoire',
// 'Croatia',
// 'Cuba',
// 'Curaçao',
// 'Cyprus',
// 'Czech Republic',
// 'Denmark',
// 'Djibouti',
// 'Dominica',
// 'Dominican Republic',
// 'Ecuador',
// 'Egypt',
// 'El Salvador',
// 'Equatorial Guinea',
// 'Eritrea',
// 'Estonia',
// 'Ethiopia',
// 'Falkland Islands (Malvinas)',
// 'Faroe Islands',
// 'Fiji',
// 'Finland',
// 'France',
// 'French Guiana',
// 'French Polynesia',
// 'French Southern Territories',
// 'Gabon',
// 'Gambia',
// 'Georgia',
// 'Ghana',
// 'Gibraltar',
// 'Greece',
// 'Greenland',
// 'Grenada',
// 'Guadeloupe',
// 'Guam',
// 'Guatemala',
// 'Guernsey',
// 'Guinea',
// 'Guinea-Bissau',
// 'Guyana',
// 'Haiti',
// 'Heard Island and McDonald Islands',
// 'Honduras',
// 'Hong Kong',
// 'Hungary',
// 'Iceland',
// 'India',
// 'Indonesia',
// 'Iran',
// 'Iraq',
// 'Ireland',
// 'Isle of Man',
// 'Israel',
// 'Italy',
// 'Jamaica',
// 'Japan',
// 'Jersey',
// 'Jordan',
// 'Kazakhstan',
// 'Kenya',
// 'Kiribati',
// 'North Korea',
// 'Sourth Korea',
// 'Kuwait',
// 'Kyrgyzstan',
// //'Lao People's Democratic Republic'
// 'Latvia',
// 'Lebanon',
// 'Lesotho',
// 'Liberia',
// 'Libya',
// 'Liechtenstein',
// 'Lithuania',
// 'Luxembourg',
// 'Macao',
// 'Republic of Northern Macedonia,',
// 'Madagascar',
// 'Malawi',
// 'Malaysia',
// 'Maldives',
// 'Mali',
// 'Malta',
// 'Marshall Islands',
// 'Martinique',
// 'Mauritania',
// 'Mauritius',
// 'Mayotte',
// 'Mexico',
// 'Federated States of Micronesia',
// 'Republic of Moldova',
// 'Monaco',
// 'Mongolia',
// 'Montenegro',
// 'Montserrat',
// 'Morocco',
// 'Mozambique',
// 'Myanmar',
// 'Namibia',
// 'Nauru',
// 'Nepal',
// 'Netherlands',
// 'New Caledonia',
// 'New Zealand',
// 'Nicaragua',
// 'Niger',
// 'Nigeria',
// 'Niue',
// 'Norfolk Island',
// 'Northern Mariana Islands',
// 'Norway',
// 'Oman',
// 'Pakistan',
// 'Palau',
// 'State of Palestine',
// 'Panama',
// 'Papua New Guinea',
// 'Paraguay',
// 'Peru',
// 'Philippines',
// 'Pitcairn',
// 'Poland',
// 'Portugal',
// 'Puerto Rico',
// 'Qatar',
// 'Réunion',
// 'Romania',
// 'Russian Federation',
// 'Rwanda',
// 'Saint Barthélemy',
// 'Ascension and Tristan da Cunha Saint Helena',
// 'Saint Kitts and Nevis',
// 'Saint Lucia',
// 'Saint Martin (French part)',
// 'Saint Pierre and Miquelon',
// 'Saint Vincent and the Grenadines',
// 'Samoa',
// 'San Marino',
// 'Sao Tome and Principe',
// 'Saudi Arabia',
// 'Senegal',
// 'Serbia',
// 'Seychelles',
// 'Sierra Leone',
// 'Singapore',
// 'Sint Maarten (Dutch part)',
// 'Slovakia',
// 'Slovenia',
// 'Solomon Islands',
// 'Somalia',
// 'South Africa',
// 'South Georgia and the South Sandwich Islands',
// 'South Sudan',
// 'Spain',
// 'Sri Lanka',
// 'Sudan',
// 'Suriname',
// 'Svalbard and Jan Mayen',
// 'Swaziland',
// 'Sweden',
// 'Switzerland',
// 'Syrian Arab Republic',
// 'Taiwan, Province of China',
// 'Tajikistan',
// 'United Republic of Tanzania',
// 'Thailand',
// 'Timor-Leste',
// 'Togo',
// 'Tokelau',
// 'Tonga',
// 'Trinidad and Tobago',
// 'Tunisia',
// 'Turkey',
// 'Turkmenistan',
// 'Turks and Caicos Islands',
// 'Tuvalu',
// 'Uganda',
// 'UKraine',
// 'United Arab Emirates',
// 'United Kingdom of Great Britain and Northern Ireland',
// 'United States Minor Outlying Islands',
// 'United States of America',
// 'Uruguay',
// 'Uzbekistan',
// 'Vanuatu',
// 'Vatican City State (Holy See)',
// 'Bolivarian Republic of Venezuela',
// 'Viet Nam',
// 'Virgin Islands, British',
// 'Virgin Islands, U.S.',
// 'Wallis and Futuna',
// 'Western Sahara',
// 'Yemen',
// 'Zambia',
// 'Zimbabwe'

//   ];

//Countries List by Continent.

export const CountryLisyByContinent = [
    
// Countries under Africa
    { name:	'Algeria', cont :'Africa'},
    { name:	'Angola', cont :'Africa'},
    { name:	'Benin', cont :'Africa'	},
    { name:	'Botswana', cont :'Africa'	},
    { name:	'Burkina Faso', cont :'Africa'	},
    { name:	'Burundi', cont :'Africa'	},
    { name:	'Cabo Verde', cont :'Africa'	},
    { name:	'Cameroon', cont :'Africa'	},
    { name:	'Central African Republic', cont :'Africa'	},
    { name:	'Chad', cont :'Africa'	},
    { name:	'Comoros', cont :'Africa'	},
    { name:	'Congo', cont :'Africa'	},
    { name:	'Cote dIvoire', cont :'Africa'	},
    { name:	'Democratic Republic of the Congo', cont :'Africa'	},
    { name:	'Djibouti', cont :'Africa'	},
    { name:	'Egypt', cont :'Africa'	},
    { name:	'Equatorial Guinea', cont :'Africa'	},
    { name:	'Eritrea', cont :'Africa'	},
    { name:	'Ethiopia', cont :'Africa'	},
    { name:	'Gabon', cont :'Africa'	},
    { name:	'Gambia', cont :'Africa'	},
    { name:	'Ghana', cont :'Africa'	},
    { name:	'Guinea', cont :'Africa'	},
    { name:	'Guinea-Bissau', cont :'Africa'	},
    { name:	'Kenya', cont :'Africa'	},
    { name:	'Lesotho', cont :'Africa'	},
    { name:	'Liberia', cont :'Africa'	},
    { name:	'Libya', cont :'Africa'	},
    { name:	'Madagascar', cont :'Africa'	},
    { name:	'Malawi', cont :'Africa'	},
    { name:	'Mali', cont :'Africa'	},
    { name:	'Mauritania', cont :'Africa'	},
    { name:	'Mauritius', cont :'Africa'	},
    { name:	'Mayotte', cont :'Africa'	},
    { name:	'Morocco', cont :'Africa'	},
    { name:	'Mozambique', cont :'Africa'	},
    { name:	'Namibia', cont :'Africa'	},
    { name:	'Niger', cont :'Africa'	},
    { name:	'Nigeria', cont :'Africa'	},
    { name:	'Rwanda', cont :'Africa'	},
    { name:	'Réunion', cont :'Africa'	},
    { name:	'Saint Helena', cont :'Africa'	},
    { name:	'Sao Tome and Principe', cont :'Africa'	},
    { name:	'Senegal', cont :'Africa'	},
    { name:	'Seychelles', cont :'Africa'	},
    { name:	'Sierra Leone', cont :'Africa'	},
    { name:	'Somalia', cont :'Africa'	},
    { name:	'South Africa', cont :'Africa'	},
    { name:	'South Sudan', cont :'Africa'	},
    { name:	'Sudan', cont :'Africa'	},
    { name:	'Swaziland', cont :'Africa'	},
    { name:	'Togo', cont :'Africa'	},
    { name:	'Tunisia', cont :'Africa'	},
    { name:	'Uganda', cont :'Africa'	},
    { name:	'United Republic of Tanzania', cont :'Africa'	},
    { name:	'Western Sahara', cont :'Africa'	},
    { name:	'Zambia', cont :'Africa'	},
    { name:	'Zimbabwe', cont :'Africa'	}, 

    //Countries under Asia

  { name:	'Afghanistan'	, cont :'Asia'	},
{ name:	'Armenia'	, cont :'Asia'	},
{ name:	'Azerbaijan'	, cont :'Asia'	},
{ name:	'Bahrain'	, cont :'Asia'	},
{ name:	'Bangladesh'	, cont :'Asia'	},
{ name:	'Bhutan'	, cont :'Asia'	},
{ name:	'Brunei Darussalam'	, cont :'Asia'	},
{ name:	'Cambodia'	, cont :'Asia'	},
{ name:	'China'	, cont :'Asia'	},
{ name:	'China, Hong Kong SAR'	, cont :'Asia'	},
{ name:	'China, Macao SAR'	, cont :'Asia'	},
{ name:	'Cyprus'	, cont :'Asia'	},
{ name:	'Dem. Peoples Republic of Korea'	, cont :'Asia'	},
{ name:	'Georgia'	, cont :'Asia'	},
{ name:	'India'	, cont :'Asia'	},
{ name:	'Indonesia'	, cont :'Asia'	},
{ name:	'Iran (Islamic Republic of)'	, cont :'Asia'	},
{ name:	'Iraq'	, cont :'Asia'	},
{ name:	'Israel'	, cont :'Asia'	},
{ name:	'Japan'	, cont :'Asia'	},
{ name:	'Jordan'	, cont :'Asia'	},
{ name:	'Kazakhstan'	, cont :'Asia'	},
{ name:	'Kuwait'	, cont :'Asia'	},
{ name:	'Kyrgyzstan'	, cont :'Asia'	},
{ name:	'Lao Peoples Democratic Republic'	, cont :'Asia'	},
{ name:	'Lebanon'	, cont :'Asia'	},
{ name:	'Malaysia'	, cont :'Asia'	},
{ name:	'Maldives'	, cont :'Asia'	},
{ name:	'Mongolia'	, cont :'Asia'	},
{ name:	'Myanmar'	, cont :'Asia'	},
{ name:	'Nepal'	, cont :'Asia'	},
{ name:	'Oman'	, cont :'Asia'	},
{ name:	'Pakistan'	, cont :'Asia'	},
{ name:	'Philippines'	, cont :'Asia'	},
{ name:	'Qatar'	, cont :'Asia'	},
{ name:	'Republic of Korea'	, cont :'Asia'	},
{ name:	'Saudi Arabia'	, cont :'Asia'	},
{ name:	'Singapore'	, cont :'Asia'	},
{ name:	'Sri Lanka'	, cont :'Asia'	},
{ name:	'State of Palestine'	, cont :'Asia'	},
{ name:	'Syrian Arab Republic'	, cont :'Asia'	},
{ name:	'Tajikistan'	, cont :'Asia'	},
{ name:	'Thailand'	, cont :'Asia'	},
{ name:	'Timor-Leste'	, cont :'Asia'	},
{ name:	'Turkey'	, cont :'Asia'	},
{ name:	'Turkmenistan'	, cont :'Asia'	},
{ name:	'United Arab Emirates'	, cont :'Asia'	},
{ name:	'Uzbekistan'	, cont :'Asia'	},
{ name:	'Viet Nam'	, cont :'Asia'	},
{ name:	'Yemen'	, cont :'Asia'	},

//Countries under Europe
{ name:	'Albania'	, cont :'Europe'	},
{ name:	'Andorra'	, cont :'Europe'	},
{ name:	'Austria'	, cont :'Europe'	},
{ name:	'Belarus'	, cont :'Europe'	},
{ name:	'Belgium'	, cont :'Europe'	},
{ name:	'Bosnia and Herzegovina'	, cont :'Europe'	},
{ name:	'Bulgaria'	, cont :'Europe'	},
{ name:	'Channel Islands'	, cont :'Europe'	},
{ name:	'Croatia'	, cont :'Europe'	},
{ name:	'Czech Republic'	, cont :'Europe'	},
{ name:	'Denmark'	, cont :'Europe'	},
{ name:	'Estonia'	, cont :'Europe'	},
{ name:	'Faeroe Islands'	, cont :'Europe'	},
{ name:	'Finland'	, cont :'Europe'	},
{ name:	'France'	, cont :'Europe'	},
{ name:	'Germany'	, cont :'Europe'	},
{ name:	'Gibraltar'	, cont :'Europe'	},
{ name:	'Greece'	, cont :'Europe'	},
{ name:	'Guernsey'	, cont :'Europe'	},
{ name:	'Holy See'	, cont :'Europe'	},
{ name:	'Hungary'	, cont :'Europe'	},
{ name:	'Iceland'	, cont :'Europe'	},
{ name:	'Ireland'	, cont :'Europe'	},
{ name:	'Isle of Man'	, cont :'Europe'	},
{ name:	'Italy'	, cont :'Europe'	},
{ name:	'Jersey'	, cont :'Europe'	},
{ name:	'Latvia'	, cont :'Europe'	},
{ name:	'Liechtenstein'	, cont :'Europe'	},
{ name:	'Lithuania'	, cont :'Europe'	},
{ name:	'Luxembourg'	, cont :'Europe'	},
{ name:	'Malta'	, cont :'Europe'	},
{ name:	'Monaco'	, cont :'Europe'	},
{ name:	'Montenegro'	, cont :'Europe'	},
{ name:	'Netherlands'	, cont :'Europe'	},
{ name:	'Norway'	, cont :'Europe'	},
{ name:	'Poland'	, cont :'Europe'	},
{ name:	'Portugal'	, cont :'Europe'	},
{ name:	'Republic of Moldova'	, cont :'Europe'	},
{ name:	'Romania'	, cont :'Europe'	},
{ name:	'Russian Federation'	, cont :'Europe'	},
{ name:	'San Marino'	, cont :'Europe'	},
{ name:	'Sark'	, cont :'Europe'	},
{ name:	'Serbia'	, cont :'Europe'	},
{ name:	'Slovakia'	, cont :'Europe'	},
{ name:	'Slovenia'	, cont :'Europe'	},
{ name:	'Spain'	, cont :'Europe'	},
{ name:	'Svalbard and Jan Mayen Islands'	, cont :'Europe'	},
{ name:	'Sweden'	, cont :'Europe'	},
{ name:	'Switzerland'	, cont :'Europe'	},
{ name:	'The former Yugoslav Republic of Macedonia'	, cont :'Europe'	},
{ name:	'Ukraine'	, cont :'Europe'	},
{ name:	'United Kingdom of Great Britain'	, cont :'Europe'	},
{ name:	'Åland Islands'	, cont :'Europe'	},


//Countries List under North America.
{ name:	'Anguilla'	, cont :'NAmerica'	},
{ name:	'Antigua and Barbuda'	, cont :'NAmerica'	},
{ name:	'Aruba'	, cont :'NAmerica'	},
{ name:	'Bahamas'	, cont :'NAmerica'	},
{ name:	'Barbados'	, cont :'NAmerica'	},
{ name:	'Belize'	, cont :'NAmerica'	},
{ name:	'Bermuda'	, cont :'NAmerica'	},
{ name:	'Bonaire, Saint Eustatius and Saba'	, cont :'NAmerica'	},
{ name:	'British Virgin Islands'	, cont :'NAmerica'	},
{ name:	'Canada'	, cont :'NAmerica'	},
{ name:	'Cayman Islands'	, cont :'NAmerica'	},
{ name:	'Costa Rica'	, cont :'NAmerica'	},
{ name:	'Cuba'	, cont :'NAmerica'	},
{ name:	'Curaçao'	, cont :'NAmerica'	},
{ name:	'Dominica'	, cont :'NAmerica'	},
{ name:	'Dominican Republic'	, cont :'NAmerica'	},
{ name:	'El Salvador'	, cont :'NAmerica'	},
{ name:	'Greenland'	, cont :'NAmerica'	},
{ name:	'Grenada'	, cont :'NAmerica'	},
{ name:	'Guadeloupe'	, cont :'NAmerica'	},
{ name:	'Guatemala'	, cont :'NAmerica'	},
{ name:	'Haiti'	, cont :'NAmerica'	},
{ name:	'Honduras'	, cont :'NAmerica'	},
{ name:	'Jamaica'	, cont :'NAmerica'	},
{ name:	'Martinique'	, cont :'NAmerica'	},
{ name:	'Mexico'	, cont :'NAmerica'	},
{ name:	'Montserrat'	, cont :'NAmerica'	},
{ name:	'Nicaragua'	, cont :'NAmerica'	},
{ name:	'Panama'	, cont :'NAmerica'	},
{ name:	'Puerto Rico'	, cont :'NAmerica'	},
{ name:	'Saint Kitts and Nevis'	, cont :'NAmerica'	},
{ name:	'Saint Lucia'	, cont :'NAmerica'	},
{ name:	'Saint Martin (French part)'	, cont :'NAmerica'	},
{ name:	'Saint Pierre and Miquelon'	, cont :'NAmerica'	},
{ name:	'Saint Vincent and the Grenadines'	, cont :'NAmerica'	},
{ name:	'Saint-Barthélemy'	, cont :'NAmerica'	},
{ name:	'Sint Maarten (Dutch part)'	, cont :'NAmerica'	},
{ name:	'Trinidad and Tobago'	, cont :'NAmerica'	},
{ name:	'Turks and Caicos Islands'	, cont :'NAmerica'	},
{ name:	'United States of America'	, cont :'NAmerica'	},
{ name:	'United States Virgin Islands'	, cont :'NAmerica'	},

//Countries under South America
{ name:	'Argentina'	, cont :'SAmerica'	},
{ name:	'Bolivia (Plurinational State of)'	, cont :'SAmerica'	},
{ name:	'Brazil'	, cont :'SAmerica'	},
{ name:	'Chile'	, cont :'SAmerica'	},
{ name:	'Colombia'	, cont :'SAmerica'	},
{ name:	'Ecuador'	, cont :'SAmerica'	},
{ name:	'Falkland Islands (Malvinas)'	, cont :'SAmerica'	},
{ name:	'French Guiana'	, cont :'SAmerica'	},
{ name:	'Guyana'	, cont :'SAmerica'	},
{ name:	'Paraguay'	, cont :'SAmerica'	},
{ name:	'Peru'	, cont :'SAmerica'	},
{ name:	'Suriname'	, cont :'SAmerica'	},
{ name:	'Uruguay'	, cont :'SAmerica'	},
{ name:	'Venezuela (Bolivarian Republic of)'	, cont :'SAmerica'	},

//Countries under Oceania

{ name:	'American Samoa'	, cont :'Oceania'	},
{ name:	'Australia'	, cont :'Oceania'	},
{ name:	'Cook Islands'	, cont :'Oceania'	},
{ name:	'Fiji'	, cont :'Oceania'	},
{ name:	'French Polynesia'	, cont :'Oceania'	},
{ name:	'Guam'	, cont :'Oceania'	},
{ name:	'Kiribati'	, cont :'Oceania'	},
{ name:	'Marshall Islands'	, cont :'Oceania'	},
{ name:	'Micronesia (Federated States of)'	, cont :'Oceania'	},
{ name:	'Nauru'	, cont :'Oceania'	},
{ name:	'New Caledonia'	, cont :'Oceania'	},
{ name:	'New Zealand'	, cont :'Oceania'	},
{ name:	'Niue'	, cont :'Oceania'	},
{ name:	'Norfolk Island'	, cont :'Oceania'	},
{ name:	'Northern Mariana Islands'	, cont :'Oceania'	},
{ name:	'Palau'	, cont :'Oceania'	},
{ name:	'Papua New Guinea'	, cont :'Oceania'	},
{ name:	'Pitcairn'	, cont :'Oceania'	},
{ name:	'Samoa'	, cont :'Oceania'	},
{ name:	'Solomon Islands'	, cont :'Oceania'	},
{ name:	'Tokelau'	, cont :'Oceania'	},
{ name:	'Tonga'	, cont :'Oceania'	},
{ name:	'Tuvalu'	, cont :'Oceania'	},
{ name:	'Vanuatu'	, cont :'Oceania'	},
{ name:	'Wallis and Futuna Islands'	, cont :'Oceania'	},



];


